# Generated by Django 6.0.5 on 2026-06-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_pending_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
