# Generated by Django 6.0.5 on 2026-06-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agency',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
