# Generated by Django 6.0.5 on 2026-05-28 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('LEASE_EXPIRY', 'Lease Expiry Warning'), ('PAYMENT_REMINDER', 'Payment Reminder'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYOUT_PROCESSED', 'Payout Processed'), ('TICKET_UPDATE', 'Maintenance Ticket Update'), ('APPLICATION_UPDATE', 'Application Update'), ('AGENCY_VERIFIED', 'Agency Verified'), ('AGENCY_REJECTED', 'Agency Rejected'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
